services:
  - type: web
    name: tech-race-challenge
    runtime: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: NODE_ENV=production npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
